name: 'dbt_flights'
version: '1.0.0'
config-version: 2

flags:
  send_anonymous_usage_stats: false
  use_colors: true

profile: 'dbt_flights'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# models: — секция, где задаются правила для всех моделей проекта.
models:
  # имя проекта (оно же name из dbt_project.yml). Всё, что внутри, относится к моделям этого проекта.
  dbt_flights:
    stg:
      +schema: stg
      +materialized: view
    cmd:
      +schema: cmd
      +materialized: table
    rep:
      +schema: rep
      +materialized: table